import Ember from 'ember';
import EmberChart from '../ember-chart';

export default EmberChart.extend({
  width:     200,
  height:    100,
  type:      'bar',
  labelPath: 'date',
  dataPath:  'price',
  options:   {
    responsive: false,
    legend:     { display: false, },
    tooltips:   { enabled: false, },
    scales:     {
      xAxes: [{
        barPercentage:      1,
        categoryPercentage: 0.5,
        gridLines:          { display: false, },
        ticks:              { display: false, },
      }],
      yAxes: [{ display: false }],
    },
  },

  model: [
    { 'price': 123, 'date': 'JAN' },
    { 'price': 321, 'date': 'FEB' },
    { 'price': 120, 'date': 'MAR' },
    { 'price': 90, 'date': 'APR' },
    { 'price': 80, 'date': 'MAY' },
  ],

  labels:   ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [{
    fillColor:        "rgba(4,33,18,1)",
    strokeColor:      "rgba(52,152,219,0.5)",
    pointColor:       "rgba(52,152,219,1)",
    markerShape:      "circle",
    pointStrokeColor: "rgba(255,255,255,1)",
    data:             [65, 8, 90, 81, 56, 55, 40,],
    title:            "2013"
  }],

  ChartOptions: {
    canvasBackgroundColor:            'rgba(255,255,255,0.00)',
    decimalSeparator:                 ".",
    thousandSeparator:                ",",
    spaceLeft:                        0,
    spaceRight:                       0,
    spaceTop:                         0,
    spaceBottom:                      0,
    canvasBorders:                    false,
    canvasBordersWidth:               1,
    canvasBordersStyle:               "solid",
    canvasBordersColor:               "rgba(0,0,0,1)",
    scaleLabel:                       "<%=value+''%>",
    yAxisMinimumInterval:             'none',
    scaleShowLabels:                  false,
    scaleShowLine:                    true,
    scaleLineStyle:                   "solid",
    scaleLineWidth:                   0,
    scaleLineColor:                   "rgba(0,0,0,0)",
    scaleOverlay:                     false,
    scaleOverride:                    false,
    scaleSteps:                       10,
    scaleStepWidth:                   10,
    scaleStartValue:                  0,
    legend:                           false,
    maxLegendCols:                    5,
    legendBlockSize:                  15,
    legendFillColor:                  'rgba(255,255,255,0.00)',
    legendColorIndicatorStrokeWidth:  1,
    legendPosX:                       -2,
    legendPosY:                       4,
    legendXPadding:                   0,
    legendYPadding:                   0,
    legendBorders:                    false,
    legendBordersWidth:               1,
    legendBordersStyle:               "solid",
    legendBordersColors:              "rgba(102,102,102,1)",
    legendBordersSpaceBefore:         5,
    legendBordersSpaceLeft:           5,
    legendBordersSpaceRight:          5,
    legendBordersSpaceAfter:          5,
    legendSpaceBeforeText:            5,
    legendSpaceLeftText:              5,
    legendSpaceRightText:             5,
    legendSpaceAfterText:             5,
    legendSpaceBetweenBoxAndText:     5,
    legendSpaceBetweenTextHorizontal: 5,
    legendSpaceBetweenTextVertical:   5,
    legendFontFamily:                 "'Open Sans'",
    legendFontStyle:                  "normal normal",
    legendFontColor:                  "rgba(0,0,0,1)",
    legendFontSize:                   15,
    showYAxisMin:                     false,
    rotateLabels:                     "smart",
    xAxisBottom:                      false,
    yAxisLeft:                        false,
    yAxisRight:                       false,
    scaleFontFamily:                  "'Open Sans'",
    scaleFontStyle:                   "normal normal",
    scaleFontColor:                   "rgba(0,0,0,1)",
    scaleFontSize:                    12,
    pointLabelFontFamily:             "'Open Sans'",
    pointLabelFontStyle:              "normal normal",
    pointLabelFontColor:              "rgba(102,102,102,1)",
    pointLabelFontSize:               12,
    angleShowLineOut:                 true,
    angleLineStyle:                   "solid",
    angleLineWidth:                   1,
    angleLineColor:                   "rgba(0,0,0,0.1)",
    percentageInnerCutout:            50,
    scaleShowGridLines:               true,
    scaleGridLineStyle:               "solid",
    scaleGridLineWidth:               1,
    scaleGridLineColor:               "rgba(0,0,0,0.1)",
    scaleXGridLinesStep:              0,
    scaleYGridLinesStep:              5,
    segmentShowStroke:                true,
    segmentStrokeStyle:               "solid",
    segmentStrokeWidth:               2,
    segmentStrokeColor:               "rgba(255,255,255,1.00)",
    datasetStroke:                    true,
    datasetFill:                      true,
    datasetStrokeStyle:               "solid",
    datasetStrokeWidth:               2,
    bezierCurve:                      true,
    bezierCurveTension:               0.4,
    pointDotStrokeStyle:              "solid",
    pointDotStrokeWidth:              1,
    pointDotRadius:                   3,
    pointDot:                         true,
    scaleTickSizeBottom:              0,
    scaleTickSizeTop:                 0,
    scaleTickSizeLeft:                0,
    scaleTickSizeRight:               0,
    barShowStroke:                    false,
    barBorderRadius:                  0,
    barStrokeStyle:                   "solid",
    barStrokeWidth:                   1,
    barValueSpacing:                  1,
    barDatasetSpacing:                0,
    scaleShowLabelBackdrop:           true,
    scaleBackdropColor:               'rgba(255,255,255,0.75)',
    scaleBackdropPaddingX:            2,
    scaleBackdropPaddingY:            2,
    animation:                        true,
    onAnimationComplete:              function() {},
  }
});



